server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou?characterEncoding=UTF-8&useSSL=false
    username: root
    password: i_am_quark_2019
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5

mybatis:
  type-aliases-package: com.leyou.order.pojo
ly:
  jwt:
    pubKeyPath: /quark/rsa/rsa.pub # 公钥地址

#    pubKeyPath: F:\quark\rsa\rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  worker:
    workerId: 1
    dataCenterId: 1
  pay:
    appID: wx8397f8696b538317
    mchID: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    httpConnectTimeoutMs: 1000
    httpReadTimeoutMs: 8000
    tradeType: NATIVE
    spbillCreateIp: 106.52.114.205
    notifyUrl: http://106.52.114.205/api/order/wxpay/notify #内网穿透 布置到服务器时,需要改成公网ip ,服务器nginx端口需要修改
#    spbillCreateIp: 127.0.0.1
#    notifyUrl: http://ueizdi.natappfree.cc/wxpay/notify #内网穿透 布置到服务器时,需要改成公网ip ,服务器nginx端口需要修改
