spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/leyou?characterEncoding=UTF-8&useSSL=false
    username: root
    password: i_am_quark_2019
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

  rabbitmq:
    host: rabbit
    username: quark
    password: i_am_quark_2019
    virtual-host: /quark
    template:
      retry:
        enabled: true
        max-interval: 210000ms
        initial-interval: 10000ms
        multiplier: 2
    publisher-confirms: true

  redis:
    port: 6379
    host: redisdb
    password: i_am_quark_2019
eureka:
  client:
    service-url:
      defaultZone: http://eureka:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15


mybatis:
  type-aliases-package: com.leyou.user.pojo
