spring:
  rabbitmq:
    host: 127.0.0.1
    username: quark
    password: i_am_quark_2019
    virtual-host: /quark
  redis:
    host: 127.0.0.1
    port: 6379
    password: i_am_quark_2019
ly:
  sms:
    accessKeyId: LTAIfBy2qBIH4ct0
    accessKeySecret: gtV32ZyTtzTnHzaAZq5Hi06V4TUHD5
    signName: 乐优商城
    verifyCodeTemplate: SMS_170842810

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
