eureka:
  client:
    service-url:
      defaultZone: http://eureka:10086/eureka
    registry-fetch-interval-seconds: 5

ly:
  jwt:
    secret: ly@Login(Auth}*^31)&yun6%f3q2 # 登录校验的密钥
    pubKeyPath: /quark/rsa/rsa.pub # 公钥地址  注意地址的写法
    priKeyPath: /quark/rsa/rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN
