eureka:
  client:
    service-url:
      defaultZone: http://eureka:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

ly:
  upload:
    endpoint: http://oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAI4FdKhpsxH2zAEexDRvcy
    accessKeySecret: LuQnQZJNps7JirefhjsWj4cKpXoKBU
    bucketName: leyou-oss-quark
    allowTypes:
      - image/jpeg
      - image/png
      - image/bmp
      - image/gif

