spring:
  redis:
    port: 6379
    host: redisdb
    password: i_am_quark_2019

eureka:
  client:
    service-url:
      defaultZone: http://eureka:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

ly:
  jwt:
    pubKeyPath: /quark/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
