spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou?characterEncoding=UTF-8&useSSL=false
    username: root
    password: i_am_quark_2019
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

  rabbitmq:
    host: 127.0.0.1
    username: quark
    password: i_am_quark_2019
    virtual-host: /quark
    template:
      retry:
        enabled: true
        max-interval: 210000ms
        initial-interval: 10000ms
        multiplier: 2
    publisher-confirms: true
    port: 5672
    #为了导入数据库专用的
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
  jackson:
    default-property-inclusion: non_null

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
